/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package asint;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 1;
  /** RegularExpression Id. */
  int natural = 2;
  /** RegularExpression Id. */
  int digito = 3;
  /** RegularExpression Id. */
  int entero = 4;
  /** RegularExpression Id. */
  int decimal = 5;
  /** RegularExpression Id. */
  int exponencial = 6;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int REAL = 8;
  /** RegularExpression Id. */
  int BOOL = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int AND = 11;
  /** RegularExpression Id. */
  int OR = 12;
  /** RegularExpression Id. */
  int NOT = 13;
  /** RegularExpression Id. */
  int TRUE = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int NULL = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int STRUCT = 20;
  /** RegularExpression Id. */
  int NEW = 21;
  /** RegularExpression Id. */
  int DELETE = 22;
  /** RegularExpression Id. */
  int READ = 23;
  /** RegularExpression Id. */
  int WRITE = 24;
  /** RegularExpression Id. */
  int NL = 25;
  /** RegularExpression Id. */
  int TYPE = 26;
  /** RegularExpression Id. */
  int CALL = 27;
  /** RegularExpression Id. */
  int PROC = 28;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 29;
  /** RegularExpression Id. */
  int LITERAL_ENTERO = 30;
  /** RegularExpression Id. */
  int LITERAL_REAL = 31;
  /** RegularExpression Id. */
  int LITERAL_CADENA = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<natural>",
    "<digito>",
    "<entero>",
    "<decimal>",
    "<exponencial>",
    "\"int\"",
    "\"real\"",
    "\"bool\"",
    "\"string\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"struct\"",
    "\"new\"",
    "\"delete\"",
    "\"read\"",
    "\"write\"",
    "\"nl\"",
    "\"type\"",
    "\"call\"",
    "\"proc\"",
    "<IDENTIFICADOR>",
    "<LITERAL_ENTERO>",
    "<LITERAL_REAL>",
    "<LITERAL_CADENA>",
    "<token of kind 33>",
    "<token of kind 34>",
    "\"{\"",
    "\"}\"",
    "\"&&\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"[\"",
    "\"]\"",
    "\"^\"",
    "\"@\"",
    "\"-\"",
    "\"+\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\".\"",
  };

}
