
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Mar 07 17:56:58 CET 2025
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int POR = 27;
  public static final int PCIERRE = 36;
  public static final int ENTERO = 3;
  public static final int LIT_REAL = 4;
  public static final int DIFERENTE = 34;
  public static final int PUNTOCOMA = 37;
  public static final int DELETE = 19;
  public static final int WRITE = 17;
  public static final int IDENTIFICADOR = 9;
  public static final int NOT = 23;
  public static final int MENORIGUAL = 33;
  public static final int AND = 21;
  public static final int IGUAL = 24;
  public static final int TYPE = 10;
  public static final int OR = 22;
  public static final int BOOL = 6;
  public static final int ARROBA = 48;
  public static final int CALL = 15;
  public static final int DIV = 28;
  public static final int IF = 12;
  public static final int MAYORIGUAL = 32;
  public static final int EOF = 0;
  public static final int AMP = 41;
  public static final int TRUE = 51;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int COMA = 38;
  public static final int LIT_STRING = 7;
  public static final int MENOS = 26;
  public static final int NULL = 50;
  public static final int MENOR = 31;
  public static final int MOD = 29;
  public static final int PUNT = 45;
  public static final int REAL = 5;
  public static final int MAYOR = 30;
  public static final int PAP = 35;
  public static final int ELSE = 13;
  public static final int PUNTO = 46;
  public static final int NL = 20;
  public static final int READ = 16;
  public static final int WHILE = 14;
  public static final int LIT_ENTERO = 2;
  public static final int COMPARACION = 49;
  public static final int PROC = 11;
  public static final int STRING = 8;
  public static final int CORC = 44;
  public static final int FALSE = 52;
  public static final int CORA = 43;
  public static final int DOBLEAMPER = 47;
  public static final int STRUCT = 42;
  public static final int LLAVEC = 40;
  public static final int LLAVEA = 39;
  public static final int MAS = 25;
}

